### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by ButchersBoy** [ButchersBoy/doobry#1]
- [ ] Add/delete databases/connections
- [ ] Selecting same connection after editing it doesn't update tab header
- [ ] Persist window size/state along with rest of layout
